// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCylJz2IAzqrucsk7oJtU5Nm_h47dSAazk',
    appId: '1:1063895312468:web:85feb166f7d32dfbe465c1',
    messagingSenderId: '1063895312468',
    projectId: 'elbialygold',
    authDomain: 'elbialygold.firebaseapp.com',
    storageBucket: 'elbialygold.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dVUQKsJe_B2wmoXz_CohOKe0jBWXt3g',
    appId: '1:1063895312468:android:7b9a70ce09348ee4e465c1',
    messagingSenderId: '1063895312468',
    projectId: 'elbialygold',
    storageBucket: 'elbialygold.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3u-btCMW6yphB0kk2OXQlKm5srS_59M',
    appId: '1:1063895312468:ios:37e201e63050eb1be465c1',
    messagingSenderId: '1063895312468',
    projectId: 'elbialygold',
    storageBucket: 'elbialygold.firebasestorage.app',
    iosBundleId: 'com.example.elbialygold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3u-btCMW6yphB0kk2OXQlKm5srS_59M',
    appId: '1:1063895312468:ios:37e201e63050eb1be465c1',
    messagingSenderId: '1063895312468',
    projectId: 'elbialygold',
    storageBucket: 'elbialygold.firebasestorage.app',
    iosBundleId: 'com.example.elbialygold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCylJz2IAzqrucsk7oJtU5Nm_h47dSAazk',
    appId: '1:1063895312468:web:2809c88ed711d873e465c1',
    messagingSenderId: '1063895312468',
    projectId: 'elbialygold',
    authDomain: 'elbialygold.firebaseapp.com',
    storageBucket: 'elbialygold.firebasestorage.app',
  );
}
