# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats (optional)
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Prepare symlinks and Flutter-specific pods
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_ios_podfile_setup

end
